### ISSUE TITLE
OptionSet.WriteOptionDescriptions crashes when Option.Description ends with a line break

### ISSUE THREAD

**Issue by jannicklange** [nano-byte/NDesk.Options#2]
Hey!
We use NDesk.Options in the [Optano.Algorithm.Tuner](https://github.com/OPTANO/optano.algorithm.tuner) package.
I tried to migrate from the old NDesk.Options to the "patched" package, since I'd like to get rid of the [NU1701] target framework warning.

After the update, some of our tests were failing. This seems to be caused by an option whose description ends with a line break ('\n').

It turns out that the OptionSet.GetLines method tries to get a substring with length '-1' when a description ends with any line break ('\r\n', '\n', 'Environment.NewLine'). The old NDesk.Options do not have this issue.

The following snippet shows the issue:

```
        static void Main(string[] args)
        {
            var optionSet = new OptionSet();
            optionSet.Add(
                "c|celp",
                () =>
                    $"Prints celp. break:{Environment.NewLine}",
                (p) => Console.WriteLine($"CELP!"));
            optionSet.Add(
                "h|help",
                () =>
                    $"Prints help. This text goes on for a while so that NDesk needs to insert line breaks somewhere...{Environment.NewLine}new line? Fine, but here is even more text ending with a LinBreak. So let's see.{Environment.NewLine}",
                (p) => Console.WriteLine($"HELP!"));
            optionSet.Add(
                "f|felp",
                () =>
                    $"Prints felp. This text goes on for a while so that NDesk needs to insert line breaks somewhere...\r\nnew line? Fine, but here is even more text ending with a carriage return. So let's see.\r\n",
                (p) => Console.WriteLine($"FELP!"));
            optionSet.Add(
                "b|belp",
                () =>
                    $"Prints belp. This text goes on for a while so that NDesk needs to insert line breaks somewhere...\r\nnew line? Fine, but here is even more text ending with a return. So let's see.\n",
                (p) => Console.WriteLine($"BELP!"));
            optionSet.WriteOptionDescriptions(Console.Out);
        }
```

Output with old NDesk.Options:
```
  -c, --celp                 Prints celp. break:

  -h, --help                 Prints help. This text goes on for a while so
                               that NDesk needs to insert line breaks somewher-
                               e...
                               new line? Fine, but here is even more text
                               ending with a LinBreak. So let's see.

  -f, --felp                 Prints felp. This text goes on for a while so
                               that NDesk needs to insert line breaks somewher-
                               e...
                               new line? Fine, but here is even more text
                               ending with a carriage return. So let's see.

  -b, --belp                 Prints belp. This text goes on for a while so
                               that NDesk needs to insert line breaks somewher-
                               e...
                               new line? Fine, but here is even more text
                               ending with a return. So let's see.

```

Output with NDesk.Options.Patched:
```
  -c, --celp                 Prints celp. break:
Unhandled exception. System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at NDesk.Options.OptionSet.GetLines(String description)+MoveNext()
   at NDesk.Options.OptionSet.WriteOptionDescriptions(TextWriter o)
   at NDeskTest.Program.Main(String[] args)
```

I already implemented a fix, for which I'll create a PR shortly.
It'd be great if you could publish a new release that includes it.

Best Regards
Jannick Lange

**Comment by bastianeicher** [comment]
Thanks for reporting this issue. I'll be happy to review your PR and publish a new release afterwards.

**Comment by jannicklange** [comment]
Thanks for the quick update!
Version 0.3.2 behaves as expected.
